"""
Prism Engine
==================
Multi-agent pipeline for automated LLM-based market research simulation.

Agent 1  — Audience Analyst & Survey Designer (2-phase: clarify → propose)
Simulation — Parallel persona-conditioned API calls (LiteLLM — model-agnostic)
Agent 2  — Aggregator & Strategist

Model configuration (via env vars or .env file):
  PRISM_AGENT_MODEL  — Agent 1 & 2  (default: claude-sonnet-4-6)
  PRISM_SIM_MODEL    — Simulation   (default: gemini/gemini-2.0-flash)

Supported providers (set matching API key env var):
  Anthropic  : ANTHROPIC_API_KEY   — claude-sonnet-4-6, claude-haiku-4-5-20251001
  Google     : GEMINI_API_KEY      — gemini/gemini-2.0-flash, gemini/gemini-1.5-pro
"""
from __future__ import annotations

import asyncio
import json
import os
import re
import statistics
from dataclasses import dataclass, field
from typing import Any

import litellm
from dotenv import load_dotenv

load_dotenv()

AGENT_MODEL = os.getenv("PRISM_AGENT_MODEL", "claude-sonnet-4-6")
SIM_MODEL   = os.getenv("PRISM_SIM_MODEL",   "gemini/gemini-2.0-flash")
EMBED_MODEL = os.getenv("PRISM_EMBED_MODEL", "text-embedding-3-small")

# If true, _chat/_achat will pass api_key=None to litellm (reads from env).
# Set PRISM_ALLOW_ENV_KEY=true for local dev / existing scripts.
ALLOW_ENV_KEY = os.getenv("PRISM_ALLOW_ENV_KEY", "false").lower() == "true"

# Suppress litellm success logs
litellm.success_callback = []
litellm.set_verbose = False


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class Segment:
    name: str
    description: str       # persona description for system prompt
    weight: float          # population weight (0-1, all segments sum to 1)
    rationale: str         # why this segment is relevant

@dataclass
class SurveyQuestion:
    id: str
    text: str
    type: str              # "likert5" | "binary" | "wtp" | "open" | "multi_select"
    scale_label: str = ""  # e.g. "1=Strongly Disagree, 5=Strongly Agree"
    options: list = field(default_factory=list)   # for multi_select
    condition: str = "neutral"                    # "neutral" | "anonymous" | "named"
    use_ssr: bool = False  # if True, elicit free-text + embed → Likert pmf (Maier et al. 2025)
    anchors: list = field(default_factory=list)   # 5 anchor statements for SSR (auto-generated by Agent 1)

@dataclass
class ClarifyQuestion:
    id: str               # stable key — GUI uses for state
    axis: str             # "geography"|"decision"|"segments"|"sensitivity"|"success_metric"|"constraints"
    text: str             # question text shown to user
    why: str              # one sentence: what this answer changes downstream (GUI tooltip)
    answer_type: str      # "text" | "single_select" | "multi_select" | "number"
    options: list         # suggested answers — GUI renders as radio/chip/checkbox
    allow_freeform: bool  # if True, GUI adds "Other..." free-text box
    skippable: bool       # if True, GUI shows "Let agent decide" button
    priority: str         # "must" | "nice" — GUI hides "nice" behind expander

@dataclass
class SimulatedResponse:
    segment_name: str
    persona_detail: str
    question_id: str
    raw_response: str
    parsed_value: Any           # numeric for likert/wtp/binary, str for open; float ev for SSR
    pmf: list | None = None     # 5-element Likert pmf from SSR; None for DLR/other types

@dataclass
class SegmentResult:
    segment: Segment
    question_summaries: dict[str, Any]   # question_id -> aggregated stats
    open_themes: list[str]

@dataclass
class AnalysisOutput:
    segment_results: list[SegmentResult]
    overall_summary: dict[str, Any]
    recommendations: list[str]
    risk_flags: list[str]
    target_segment: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _chat(
    model: str, system: str, user: str,
    max_tokens: int = 2048, temperature: float = 0.7,
    api_key: str | None = None,
) -> str:
    """Synchronous single-turn chat via LiteLLM with retry on 429."""
    import time
    if api_key is None and not ALLOW_ENV_KEY:
        raise RuntimeError(
            "No API key provided. Set PRISM_ALLOW_ENV_KEY=true for local dev "
            "or pass api_key explicitly."
        )
    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": user})
    delay = 20.0
    call_kwargs: dict = dict(
        model=model,
        messages=messages,
        max_tokens=max_tokens,
        temperature=temperature,
    )
    if api_key is not None:
        call_kwargs["api_key"] = api_key
    for attempt in range(8):
        try:
            response = litellm.completion(**call_kwargs)
            return response.choices[0].message.content.strip()
        except litellm.exceptions.RateLimitError:
            if attempt == 7:
                raise
            time.sleep(delay)
            delay = min(delay * 1.5, 120.0)


async def _achat(
    model: str, system: str, user: str,
    max_tokens: int = 256, temperature: float = 1.0,
    api_key: str | None = None,
) -> str:
    """Async single-turn chat via LiteLLM."""
    if api_key is None and not ALLOW_ENV_KEY:
        raise RuntimeError(
            "No API key provided. Set PRISM_ALLOW_ENV_KEY=true for local dev "
            "or pass api_key explicitly."
        )
    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": user})
    call_kwargs: dict = dict(
        model=model,
        messages=messages,
        max_tokens=max_tokens,
        temperature=temperature,
    )
    if api_key is not None:
        call_kwargs["api_key"] = api_key
    response = await litellm.acompletion(**call_kwargs)
    return response.choices[0].message.content.strip()


def _strip_json(raw: str) -> dict:
    # Find the outermost JSON object even if wrapped in markdown fences or prose
    start = raw.find("{")
    end = raw.rfind("}")
    if start == -1 or end == -1:
        raise ValueError(f"No JSON object found in response:\n{raw[:500]}")
    return json.loads(raw[start:end + 1])


# ---------------------------------------------------------------------------
# Agent 1 — Phase A: Clarify
# ---------------------------------------------------------------------------

AGENT1_CLARIFY_SYSTEM = """\
You are a market-research consultant scoping a multi-agent perception study.
Read the user's policy/product description and identify only what is genuinely missing
before a survey can be designed. Do NOT generate personas or survey questions — that is Phase B.

Output ONLY valid JSON. No markdown fences, no prose. Exact schema:
{
  "questions": [
    {
      "id": "string — short snake_case, unique within this response",
      "axis": "one of: geography | decision | segments | sensitivity | success_metric | constraints",
      "text": "the question to show the user",
      "why": "one sentence: what this answer changes downstream (shown as GUI tooltip)",
      "answer_type": "one of: text | single_select | multi_select | number",
      "options": ["suggested answer 1", "suggested answer 2", ...],
      "allow_freeform": true or false,
      "skippable": true or false,
      "priority": "must or nice"
    }
  ]
}

Axis definitions:
  geography      — target market, country, region, currency context
  decision       — what the user will DO with results (launch, adjust pricing, inform policy)
  segments       — known stakeholder groups to include or exclude
  sensitivity    — is the topic taboo / socially loaded enough to warrant anonymous vs named framing?
  success_metric — what outcome counts as "good" (adoption %, WTP threshold, attitudinal shift)
  constraints    — budget, timeline, regulatory levers that bound realism

Rules:
1. Only ask where the input is genuinely unclear. If the user already stated it, skip that axis.
2. Maximum 5 questions total. Prefer 2–3. Quality over coverage.
3. Every question MUST have 3–6 items in "options" — realistic suggested answers the user can click.
   Even for answer_type "text", include options as quick-pick suggestions and set allow_freeform=true.
4. answer_type guide:
   - single_select  → exactly one answer expected (geography, decision, success_metric)
   - multi_select   → several may apply (segments, constraints)
   - text           → open-ended nuance; always pair with options + allow_freeform=true
   - number         → numeric threshold (e.g. target sample N, WTP ceiling)
5. priority "must" → answer is structurally required for survey design (e.g. geography determines
   currency). Mark at most 3 as "must"; default to "nice".
6. skippable=true → user can click "Let agent decide" and skip; engine will infer from context.
   Set skippable=false only when the absence would make the survey non-functional.
7. sensitivity axis is special: probe whether the topic warrants anon/named SDB framing unless
   the input already makes it obvious (clearly taboo → auto-confirmed, skip asking; clearly benign
   → still ask, because it changes survey design).
8. The "why" field must name a concrete downstream effect, not just restate the question.

One-shot example (coffee-brand pricing study — adapt schema, not content):
Input: "We sell specialty coffee in Taipei. Thinking of raising price from NT$120 to NT$160."
Output:
{
  "questions": [
    {
      "id": "target_segment",
      "axis": "segments",
      "text": "Which customer groups matter most for this pricing decision?",
      "why": "Segments determine persona demographics and weight; missing this risks a generic result.",
      "answer_type": "multi_select",
      "options": ["Daily office commuters", "Weekend café dwellers", "Student budget buyers", "Specialty-coffee enthusiasts", "Delivery app users"],
      "allow_freeform": true,
      "skippable": true,
      "priority": "must"
    },
    {
      "id": "decision_goal",
      "axis": "decision",
      "text": "What will you do with the simulation results?",
      "why": "Decides whether Agent 2 frames recommendations around revenue optimization or brand risk.",
      "answer_type": "single_select",
      "options": ["Decide whether to raise the price at all", "Choose how to communicate the increase", "Identify which segment to target first", "Benchmark against competitor pricing"],
      "allow_freeform": true,
      "skippable": false,
      "priority": "must"
    },
    {
      "id": "sensitivity_check",
      "axis": "sensitivity",
      "text": "Is price sensitivity something customers might under-report in a non-anonymous survey?",
      "why": "Determines whether to include an anonymous vs named SDB question pair.",
      "answer_type": "single_select",
      "options": ["Yes — social pressure to seem non-price-sensitive", "Unlikely — customers are candid about price", "Unsure"],
      "allow_freeform": false,
      "skippable": true,
      "priority": "nice"
    }
  ]
}
"""

_CONDITION_PREFIX = {
    "anonymous": (
        "IMPORTANT CONTEXT: This response is collected fully anonymously. "
        "No name, IP address, or identifying metadata will ever be linked to your answer. "
        "Be completely honest.\n\n"
    ),
    "named": (
        "IMPORTANT CONTEXT: Your real name and ID will be recorded alongside this response "
        "and may be reviewed by authorities or made public. "
        "Answer as you would in a formal, non-anonymous setting.\n\n"
    ),
    "neutral": "",
}


def run_agent1_clarify(input_text: str, api_key: str | None = None) -> list[ClarifyQuestion]:
    """Phase A — return adaptive clarifying questions as structured ClarifyQuestion list."""
    raw = _chat(
        model=AGENT_MODEL,
        system=AGENT1_CLARIFY_SYSTEM,
        user=f"Policy/Product Description:\n\n{input_text}",
        max_tokens=1024,
        temperature=0.3,
        api_key=api_key,
    )
    data = _strip_json(raw)
    return [
        ClarifyQuestion(
            id=q["id"],
            axis=q["axis"],
            text=q["text"],
            why=q["why"],
            answer_type=q["answer_type"],
            options=q.get("options", []),
            allow_freeform=q.get("allow_freeform", True),
            skippable=q.get("skippable", True),
            priority=q.get("priority", "nice"),
        )
        for q in data["questions"]
    ]


def format_clarifications(questions: list[ClarifyQuestion], answers: dict[str, str]) -> str:
    """Flatten answered ClarifyQuestion list into a text block for Phase B.

    answers maps question id → answer string. "__SKIP__" values are omitted.
    """
    lines = []
    for q in questions:
        ans = answers.get(q.id, "__SKIP__")
        if ans == "__SKIP__":
            continue
        lines.append(f"[{q.axis}] {q.text}\nAnswer: {ans}")
    return "\n\n".join(lines)


# ---------------------------------------------------------------------------
# Agent 1 — Phase B: Propose
# ---------------------------------------------------------------------------

AGENT1_PROPOSE_SYSTEM = """\
You are a market research expert. Using the product/policy description and the user's
clarification answers, design a simulation study.

Your output must be ONLY valid JSON in this exact schema (no markdown fences, no extra text):
{
  "segments": [
    {
      "name": "short label",
      "description": "You are a [detailed persona — age, gender, location, income, occupation, lifestyle, relevant values and concerns]. Answer all survey questions as this person would, honestly and in character.",
      "weight": 0.25,
      "rationale": "why this segment matters for this product/policy"
    }
  ],
  "questions": [
    {
      "id": "q1",
      "text": "question text",
      "type": "likert5",
      "scale_label": "1=Strongly Disagree, 5=Strongly Agree",
      "options": [],
      "condition": "neutral",
      "use_ssr": true,
      "anchors": [
        "I strongly disagree with this.",
        "I somewhat disagree with this.",
        "I neither agree nor disagree.",
        "I somewhat agree with this.",
        "I strongly agree with this."
      ]
    },
    {
      "id": "q_behavior_anon",
      "text": "How often do you use pirated/unauthorized digital content?",
      "type": "likert5",
      "scale_label": "1=Never, 5=Very Often",
      "options": [],
      "condition": "anonymous"
    },
    {
      "id": "q_behavior_named",
      "text": "How often do you use pirated/unauthorized digital content?",
      "type": "likert5",
      "scale_label": "1=Never, 5=Very Often",
      "options": [],
      "condition": "named"
    },
    {
      "id": "q_drivers",
      "text": "Why do you choose unauthorized content over paid alternatives? Select all that apply.",
      "type": "multi_select",
      "scale_label": "",
      "options": ["Price too high", "Content unavailable legally", "Convenience", "Peer influence", "Copyright laws unfair", "No perceived harm"],
      "condition": "neutral"
    },
    {
      "id": "q_wtp",
      "text": "What is the maximum monthly subscription fee (in NT$) at which you would switch fully to legal content?",
      "type": "wtp",
      "scale_label": "Respond with a number only, in NT$. If you would never switch, reply 0.",
      "options": [],
      "condition": "neutral"
    },
    {
      "id": "q_open",
      "text": "In 1-2 sentences, what is your main concern or hope about digital content access and piracy?",
      "type": "open",
      "scale_label": "",
      "options": [],
      "condition": "neutral"
    }
  ]
}

Rules:
- Use 3 to 5 segments. Weights must sum to exactly 1.0.
- Generate 12 to 15 questions total.
- Prefer Likert-5 questions (quantifiable, supports statistical inference).
- REQUIRED: Include exactly one matched pair of questions measuring the SAME underlying behavior,
  one with condition "anonymous" and one with condition "named". Their ids MUST end with
  "_anon" and "_named" respectively (same prefix). This is the social-desirability bias pair.
- REQUIRED: Include at least one "multi_select" question with 4-6 options in the "options" array.
  Respondents pick all that apply; reply format is comma-separated option letters (A, B, C...).
- REQUIRED: End with exactly one question of type "open".
- All other questions use condition "neutral".
- Persona descriptions must be vivid and realistic (2-4 sentences), written in second person.
- Questions must be directly relevant to the specific product/policy described.
- Do not use generic or placeholder text.
- The example questions above are illustrative only — replace them with questions relevant to the input.
- For likert5 questions where response distribution shape matters (perception, attitude, intent, frequency),
  set "use_ssr": true and supply 5 "anchors": short first-person sentences spanning the scale from
  lowest to highest intensity. Anchors must be domain-specific to this question, not generic.
  Example for a piracy frequency question: ["I never use pirated content.", "I rarely use it.",
  "I use it sometimes.", "I use it quite often.", "I use pirated content very frequently."]
- For purely factual or WTP questions where the midpoint is less meaningful, set "use_ssr": false
  and omit anchors (or leave as []).
"""


def run_agent1_propose(
    input_text: str, clarifications: str = "", api_key: str | None = None
) -> tuple[list[Segment], list[SurveyQuestion]]:
    """Phase B — generate segment + question proposal from description and optional clarifications."""
    user_content = f"Product/Policy Description:\n{input_text}"
    if clarifications:
        user_content += f"\n\nClarification Answers:\n{clarifications}"

    raw = _chat(model=AGENT_MODEL, system=AGENT1_PROPOSE_SYSTEM, user=user_content, max_tokens=8192, api_key=api_key)
    data = _strip_json(raw)

    segments = [
        Segment(
            name=s["name"],
            description=s["description"],
            weight=float(s["weight"]),
            rationale=s["rationale"],
        )
        for s in data["segments"]
    ]
    questions = [
        SurveyQuestion(
            id=q["id"],
            text=q["text"],
            type=q["type"],
            scale_label=q.get("scale_label", ""),
            options=q.get("options", []),
            condition=q.get("condition", "neutral"),
            use_ssr=q.get("use_ssr", False),
            anchors=q.get("anchors", []),
        )
        for q in data["questions"]
    ]
    return segments, questions


def run_agent1(input_text: str, api_key: str | None = None) -> tuple[list[Segment], list[SurveyQuestion]]:
    """Single-shot Agent 1 (no clarification step — used in automated pipeline)."""
    return run_agent1_propose(input_text, api_key=api_key)


# ---------------------------------------------------------------------------
# SSR (Semantic Similarity Rating) helpers — Maier et al. 2025
# ---------------------------------------------------------------------------

_GENERIC_ANCHORS_AGREEMENT = [
    "I strongly disagree with this.",
    "I somewhat disagree with this.",
    "I neither agree nor disagree.",
    "I somewhat agree with this.",
    "I strongly agree with this.",
]
_GENERIC_ANCHORS_FREQUENCY = [
    "I never do this.",
    "I rarely do this.",
    "I sometimes do this.",
    "I often do this.",
    "I very frequently or always do this.",
]
_GENERIC_ANCHORS_LIKELIHOOD = [
    "This is very unlikely to happen for me.",
    "This is somewhat unlikely for me.",
    "I'm unsure or indifferent about this.",
    "This is somewhat likely for me.",
    "This is very likely to happen for me.",
]

# Module-level cache: anchor tuple → list of embedding vectors (populated once per run)
_ANCHOR_EMBED_CACHE: dict[tuple[str, ...], list[list[float]]] = {}


def _resolve_anchors(q: SurveyQuestion) -> list[str]:
    """Return q.anchors if Agent 1 provided 5; else pick generic family from scale_label."""
    if q.anchors and len(q.anchors) == 5:
        return q.anchors
    label = q.scale_label.lower()
    if any(w in label for w in ("often", "never", "frequent", "rare")):
        return _GENERIC_ANCHORS_FREQUENCY
    if any(w in label for w in ("likely", "unlikely", "intent", "purchase")):
        return _GENERIC_ANCHORS_LIKELIHOOD
    return _GENERIC_ANCHORS_AGREEMENT


def _cosine(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = sum(x * x for x in a) ** 0.5
    norm_b = sum(x * x for x in b) ** 0.5
    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0
    return dot / (norm_a * norm_b)


async def _aembed(text: str) -> list[float]:
    """Embed a single string via litellm (uses OPENAI_API_KEY from env)."""
    resp = await litellm.aembedding(model=EMBED_MODEL, input=[text])
    return resp.data[0]["embedding"]


async def _ssr_score(response_text: str, anchors: list[str]) -> tuple[list[float], float]:
    """Map a free-text response to a Likert pmf via cosine similarity to anchors.

    Returns (pmf, expected_value) where pmf is length-5 and ev is in [1, 5].
    Uses ε=0, T=1 defaults from Maier et al. 2025.
    """
    key = tuple(anchors)
    if key not in _ANCHOR_EMBED_CACHE:
        _ANCHOR_EMBED_CACHE[key] = [await _aembed(a) for a in anchors]
    anchor_vecs = _ANCHOR_EMBED_CACHE[key]
    resp_vec = await _aembed(response_text)
    sims = [_cosine(resp_vec, av) for av in anchor_vecs]
    min_sim = min(sims)
    shifted = [max(0.0, s - min_sim) for s in sims]
    total = sum(shifted) or 1.0
    pmf = [s / total for s in shifted]
    ev = sum((i + 1) * p for i, p in enumerate(pmf))
    return pmf, ev


async def _prewarm_anchor_cache(questions: list[SurveyQuestion]) -> None:
    """Pre-embed anchors for all SSR questions before simulation fan-out."""
    seen: set[tuple[str, ...]] = set()
    for q in questions:
        if q.type == "likert5" and q.use_ssr:
            anchors = _resolve_anchors(q)
            key = tuple(anchors)
            if key not in seen and key not in _ANCHOR_EMBED_CACHE:
                seen.add(key)
                _ANCHOR_EMBED_CACHE[key] = [await _aembed(a) for a in anchors]


# ---------------------------------------------------------------------------
# Simulation Layer
# ---------------------------------------------------------------------------

def _build_question_instruction(q: SurveyQuestion) -> str:
    prefix = _CONDITION_PREFIX.get(q.condition, "")
    if q.type == "likert5":
        if q.use_ssr:
            body = (
                f"{q.text}\n"
                f"In 1-2 sentences, describe honestly and specifically how you feel about this. "
                f"Do not mention numbers or rating scales."
            )
        else:
            body = (
                f"{q.text}\n"
                f"Rate on a scale of 1 to 5. {q.scale_label}. "
                f"Reply with a single integer (1, 2, 3, 4, or 5) and nothing else."
            )
    elif q.type == "binary":
        body = (
            f"{q.text}\n"
            f"{q.scale_label}. Reply with exactly 'yes' or 'no' and nothing else."
        )
    elif q.type == "wtp":
        body = (
            f"{q.text}\n"
            f"{q.scale_label}. Reply with a number only (no currency symbol, no text). "
            f"If you would not pay anything, reply with 0."
        )
    elif q.type == "multi_select":
        letters = [chr(ord("A") + i) for i in range(len(q.options))]
        option_lines = "\n".join(f"  {l}: {o}" for l, o in zip(letters, q.options))
        body = (
            f"{q.text}\n"
            f"Options:\n{option_lines}\n"
            f"Reply with the letters of ALL options that apply, comma-separated (e.g. A,C,E). "
            f"Reply with letters only, no other text."
        )
    else:
        body = f"{q.text}\nAnswer in 1-2 sentences. Be honest and specific."
    return prefix + body


def _parse_response(q: SurveyQuestion, raw: str) -> Any:
    text = raw.strip().lower()
    if q.type == "likert5":
        if q.use_ssr:
            return raw.strip()  # SSR: return free text; _simulate_one replaces with float ev
        match = re.search(r"[1-5]", text)
        return int(match.group()) if match else None
    elif q.type == "binary":
        if "yes" in text:
            return 1
        elif "no" in text:
            return 0
        return None
    elif q.type == "wtp":
        match = re.search(r"\d[\d,]*", text)
        return float(match.group().replace(",", "")) if match else None
    elif q.type == "multi_select":
        letters = [chr(ord("A") + i) for i in range(len(q.options))]
        selected = []
        for letter in re.findall(r"[A-Za-z]", raw):
            ul = letter.upper()
            if ul in letters:
                idx = ord(ul) - ord("A")
                if idx < len(q.options):
                    selected.append(q.options[idx])
        return selected if selected else None
    else:
        return raw.strip()


async def _simulate_one(
    segment: Segment,
    question: SurveyQuestion,
    semaphore: asyncio.Semaphore,
    api_key: str | None = None,
    max_retries: int = 10,
) -> SimulatedResponse:
    instruction = _build_question_instruction(question)
    delay = 20.0
    for attempt in range(max_retries):
        try:
            async with semaphore:
                raw = await _achat(
                    model=SIM_MODEL,
                    system=segment.description,
                    user=instruction,
                    max_tokens=256,
                    temperature=1.0,
                    api_key=api_key,
                )
            break
        except litellm.exceptions.RateLimitError:
            if attempt == max_retries - 1:
                raise
            await asyncio.sleep(delay)
            delay = min(delay * 1.5, 120.0)
    if question.type == "likert5" and question.use_ssr:
        anchors = _resolve_anchors(question)
        pmf, ev = await _ssr_score(raw, anchors)
        return SimulatedResponse(
            segment_name=segment.name,
            persona_detail=segment.description[:80] + "...",
            question_id=question.id,
            raw_response=raw,
            parsed_value=ev,
            pmf=pmf,
        )
    return SimulatedResponse(
        segment_name=segment.name,
        persona_detail=segment.description[:80] + "...",
        question_id=question.id,
        raw_response=raw,
        parsed_value=_parse_response(question, raw),
        pmf=None,
    )


async def run_simulation_async(
    segments: list[Segment],
    questions: list[SurveyQuestion],
    responses_per_cell: int = 10,
    max_concurrent: int = 3,
    api_key: str | None = None,
    progress_callback=None,
) -> list[SimulatedResponse]:
    semaphore = asyncio.Semaphore(max_concurrent)

    # Pre-embed anchors for SSR questions (once per question, reused across all respondents)
    await _prewarm_anchor_cache(questions)

    total = len(segments) * len(questions) * responses_per_cell
    completed = 0

    async def _sim_with_progress(segment, question):
        nonlocal completed
        result = await _simulate_one(segment, question, semaphore, api_key=api_key)
        completed += 1
        if progress_callback is not None:
            progress_callback(completed, total)
        return result

    tasks = [
        _sim_with_progress(segment, question)
        for segment in segments
        for question in questions
        for _ in range(responses_per_cell)
    ]
    results = await asyncio.gather(*tasks, return_exceptions=True)
    return [r for r in results if isinstance(r, SimulatedResponse)]


def run_simulation(
    segments: list[Segment],
    questions: list[SurveyQuestion],
    responses_per_cell: int = 10,
    max_concurrent: int = 3,
    api_key: str | None = None,
    progress_callback=None,
) -> list[SimulatedResponse]:
    return asyncio.run(
        run_simulation_async(
            segments, questions, responses_per_cell, max_concurrent,
            api_key=api_key, progress_callback=progress_callback,
        )
    )


# ---------------------------------------------------------------------------
# Agent 2: Aggregator & Strategist
# ---------------------------------------------------------------------------

def _aggregate_responses(
    responses: list[SimulatedResponse],
    segments: list[Segment],
    questions: list[SurveyQuestion],
) -> list[SegmentResult]:
    seg_map = {s.name: s for s in segments}
    q_map = {q.id: q for q in questions}

    by_seg_q: dict[tuple[str, str], list[SimulatedResponse]] = {}
    for r in responses:
        by_seg_q.setdefault((r.segment_name, r.question_id), []).append(r)

    # Find SDB-paired question ids: ids ending in _anon/_named
    # Match on stripped base name (remove leading q{N}_ and trailing _anon/_named)
    def _base(qid: str) -> str:
        s = re.sub(r'^q\d+_', '', qid)   # strip leading q1_, q3_, etc.
        s = re.sub(r'_(anon|named)$', '', s)
        return s

    named_ids = {q.id for q in questions if q.id.endswith("_named")}
    anon_ids  = {q.id for q in questions if q.id.endswith("_anon")}
    sdb_pairs: list[tuple[str, str]] = []
    for aid in anon_ids:
        base_a = _base(aid)
        match = next((nid for nid in named_ids if _base(nid) == base_a), None)
        if match:
            sdb_pairs.append((aid, match))

    segment_results = []
    for seg in segments:
        q_summaries: dict[str, Any] = {}
        open_themes: list[str] = []

        for q in questions:
            cell = by_seg_q.get((seg.name, q.id), [])
            values = [r.parsed_value for r in cell if r.parsed_value is not None]

            if q.type in ("likert5", "wtp"):
                if values:
                    numeric = [float(v) for v in values]
                    entry: dict[str, Any] = {
                        "type": q.type,
                        "question": q.text,
                        "condition": q.condition,
                        "n": len(numeric),
                        "mean": round(sum(numeric) / len(numeric), 2),
                        "min": round(min(numeric), 2),
                        "max": round(max(numeric), 2),
                    }
                    if len(numeric) >= 2:
                        entry["sd"] = round(statistics.stdev(numeric), 2)
                    if q.type == "likert5" and q.use_ssr:
                        cell_pmfs = [r.pmf for r in cell if r.pmf is not None]
                        if cell_pmfs:
                            n_p = len(cell_pmfs)
                            entry["pmf_mean"] = [
                                round(sum(p[i] for p in cell_pmfs) / n_p, 4)
                                for i in range(5)
                            ]
                    q_summaries[q.id] = entry
            elif q.type == "binary":
                if values:
                    q_summaries[q.id] = {
                        "type": "binary",
                        "question": q.text,
                        "condition": q.condition,
                        "n": len(values),
                        "pct_yes": round(100 * sum(values) / len(values), 1),
                    }
            elif q.type == "multi_select":
                all_lists = [v for v in values if isinstance(v, list)]
                if all_lists:
                    all_opts = q_map[q.id].options
                    rates = {}
                    for opt in all_opts:
                        count = sum(1 for lst in all_lists if opt in lst)
                        rates[opt] = round(100 * count / len(all_lists), 1)
                    q_summaries[q.id] = {
                        "type": "multi_select",
                        "question": q.text,
                        "condition": q.condition,
                        "n": len(all_lists),
                        "rates": rates,
                    }
            else:
                open_themes.extend(r.raw_response for r in cell if r.raw_response)

        # Compute SDB gaps for this segment
        sdb_gaps: dict[str, float] = {}
        for aid, nid in sdb_pairs:
            anon_stats = q_summaries.get(aid)
            named_stats = q_summaries.get(nid)
            if anon_stats and named_stats and "mean" in anon_stats and "mean" in named_stats:
                gap = round(anon_stats["mean"] - named_stats["mean"], 2)
                prefix = aid[:-5]
                sdb_gaps[prefix] = gap
        if sdb_gaps:
            q_summaries["__sdb_gaps__"] = sdb_gaps

        segment_results.append(SegmentResult(
            segment=seg_map[seg.name],
            question_summaries=q_summaries,
            open_themes=open_themes[:3],
        ))

    return segment_results


AGENT2_SYSTEM = """\
You are a senior market research analyst. Based on the survey simulation results below,
produce a structured strategic report.

Return ONLY valid JSON with this schema (no markdown fences):
{
  "overall_summary": {
    "weighted_reception_score": 3.4,
    "key_insight": "one-sentence headline finding"
  },
  "recommendations": [
    "actionable recommendation 1",
    "actionable recommendation 2",
    "actionable recommendation 3"
  ],
  "risk_flags": [
    "risk or concern 1",
    "risk or concern 2"
  ],
  "target_segment": "name of the most receptive segment"
}

Be specific and ground every recommendation in the data. Do not be generic.
If the data contains paired anonymous/named questions, comment explicitly on the size
of the social desirability gap and which segments hide their behavior most.
"""


def run_agent2(
    segment_results: list[SegmentResult],
    questions: list[SurveyQuestion],
    input_text: str,
    api_key: str | None = None,
) -> AnalysisOutput:
    summary_lines = [f"Product/Policy: {input_text}\n"]
    for sr in segment_results:
        summary_lines.append(f"\nSegment: {sr.segment.name} (weight={sr.segment.weight:.0%})")
        for qid, stats in sr.question_summaries.items():
            if qid == "__sdb_gaps__":
                for pair_prefix, gap in stats.items():
                    summary_lines.append(f"  [SDB gap: {pair_prefix}] anon-named mean diff = {gap:+.2f} (positive = higher disclosure when anonymous)")
                continue
            q_text = stats.get("question", qid)
            cond = stats.get("condition", "neutral")
            cond_tag = f" [{cond}]" if cond != "neutral" else ""
            if stats["type"] == "likert5":
                summary_lines.append(f"  [{qid}]{cond_tag} {q_text[:60]} -> mean={stats['mean']}/5 (n={stats['n']})")
            elif stats["type"] == "binary":
                summary_lines.append(f"  [{qid}]{cond_tag} {q_text[:60]} -> {stats['pct_yes']}% yes (n={stats['n']})")
            elif stats["type"] == "wtp":
                summary_lines.append(f"  [{qid}]{cond_tag} {q_text[:60]} -> mean WTP=NT${stats['mean']} (n={stats['n']})")
            elif stats["type"] == "multi_select":
                top = sorted(stats["rates"].items(), key=lambda x: -x[1])[:3]
                top_str = ", ".join(f"{o}:{r}%" for o, r in top)
                summary_lines.append(f"  [{qid}] {q_text[:60]} -> top drivers: {top_str} (n={stats['n']})")
        for t in sr.open_themes[:2]:
            safe_t = t[:120].replace('"', "'").replace('\\', '')
            summary_lines.append(f"  [open] '{safe_t}'")

    raw = _chat(
        model=AGENT_MODEL,
        system=AGENT2_SYSTEM,
        user="\n".join(summary_lines),
        max_tokens=4096,
        temperature=0.5,
        api_key=api_key,
    )
    data = _strip_json(raw)

    return AnalysisOutput(
        segment_results=segment_results,
        overall_summary=data.get("overall_summary", {}),
        recommendations=data.get("recommendations", []),
        risk_flags=data.get("risk_flags", []),
        target_segment=data.get("target_segment", ""),
    )


# ---------------------------------------------------------------------------
# Full pipeline
# ---------------------------------------------------------------------------

def run_pipeline(
    input_text: str,
    responses_per_cell: int = 10,
    progress_callback=None,
    clarifications: str = "",
    api_key: str | None = None,
) -> AnalysisOutput:
    """
    End-to-end pipeline.
    Pass clarifications (from run_agent1_clarify user answers) for richer personas.
    progress_callback(step: str, pct: float) called at each stage.
    """
    def cb(step, pct):
        if progress_callback:
            progress_callback(step, pct)

    cb("Agent 1: Analyzing audience and designing survey...", 0.05)
    segments, questions = run_agent1_propose(input_text, clarifications, api_key=api_key)

    cb("Simulation: Running synthetic respondents...", 0.25)
    responses = run_simulation(segments, questions, responses_per_cell=responses_per_cell, api_key=api_key)

    cb("Aggregating results...", 0.80)
    segment_results = _aggregate_responses(responses, segments, questions)

    cb("Agent 2: Generating strategic recommendations...", 0.90)
    output = run_agent2(segment_results, questions, input_text, api_key=api_key)

    cb("Done.", 1.0)
    return output
